/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Exception.InputKosongException;
import control.PenyewaanControl;
import control.CustomerControl;
import control.KendaraanControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Customer;
import model.Kendaraan;
import model.Penyewaan;

/**
 * Nama : Reynold Kunarto 
 * NPM : 210711015
 * 
 * Nama : Febiola Ika Putri Wibowo
 * NPM : 210711023
 */
/**
 *
 * @author VICTUS
 */
public class PenyewaanView extends javax.swing.JFrame {

    /**
     * Creates new form PenyewaanView
     */
    private KendaraanControl kendaraanControl;
    private PenyewaanControl penyewaanControl;
    private CustomerControl customerControl;
    String action = null;
    List<Kendaraan> listKendaraan;
    List<Customer> listCustomer;
    int selectedId = 0;
    public PenyewaanView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        kendaraanControl = new KendaraanControl();
        customerControl = new CustomerControl();
        penyewaanControl = new PenyewaanControl();
        showPenyewaan();
        setKendaraanToDropdown();
        setCustomerToDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        kelompokPanel = new javax.swing.JPanel();
        kelompokLabel = new javax.swing.JLabel();
        npm1Label = new javax.swing.JLabel();
        npm2Label = new javax.swing.JLabel();
        actionBar = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        inputPanel = new javax.swing.JPanel();
        kendaraanLabel = new javax.swing.JLabel();
        kendaraanDropdown = new javax.swing.JComboBox<>();
        customerLabel = new javax.swing.JLabel();
        customerDropdown = new javax.swing.JComboBox<>();
        lamaLabel = new javax.swing.JLabel();
        lamaInput = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        hargaInput = new javax.swing.JTextField();
        fasilitasLabel = new javax.swing.JLabel();
        snackCheck = new javax.swing.JCheckBox();
        maskerCheck = new javax.swing.JCheckBox();
        tissueCheck = new javax.swing.JCheckBox();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenyewaan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(204, 204, 204));
        container.setForeground(new java.awt.Color(0, 0, 0));

        header.setBackground(new java.awt.Color(255, 204, 0));

        kelompokLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kelompokLabel.setText("Kelompok 5");

        npm1Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        npm1Label.setText("210711015");

        npm2Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        npm2Label.setText("210711023");

        javax.swing.GroupLayout kelompokPanelLayout = new javax.swing.GroupLayout(kelompokPanel);
        kelompokPanel.setLayout(kelompokPanelLayout);
        kelompokPanelLayout.setHorizontalGroup(
            kelompokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelompokPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(npm1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npm2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(kelompokPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(kelompokLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kelompokPanelLayout.setVerticalGroup(
            kelompokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelompokPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(kelompokLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kelompokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npm2Label)
                    .addComponent(npm1Label))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(938, Short.MAX_VALUE)
                .addComponent(kelompokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kelompokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        actionBar.setBackground(new java.awt.Color(51, 51, 51));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionBarLayout = new javax.swing.GroupLayout(actionBar);
        actionBar.setLayout(actionBarLayout);
        actionBarLayout.setHorizontalGroup(
            actionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionBarLayout.createSequentialGroup()
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn))
                    .addGroup(actionBarLayout.createSequentialGroup()
                        .addGroup(actionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn)
                            .addComponent(deleteBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        actionBarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, deleteBtn, editBtn});

        actionBarLayout.setVerticalGroup(
            actionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(searchBtn)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));

        kendaraanLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        kendaraanLabel.setForeground(new java.awt.Color(50, 50, 50));
        kendaraanLabel.setText("Kendaraan");

        kendaraanDropdown.setBackground(new java.awt.Color(153, 153, 153));
        kendaraanDropdown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kendaraanDropdown.setForeground(new java.awt.Color(51, 51, 51));

        customerLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(50, 50, 50));
        customerLabel.setText("Nama Customer");

        customerDropdown.setBackground(new java.awt.Color(153, 153, 153));
        customerDropdown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerDropdown.setForeground(new java.awt.Color(51, 51, 51));

        lamaLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lamaLabel.setForeground(new java.awt.Color(50, 50, 50));
        lamaLabel.setText("Lama Sewa");

        lamaInput.setBackground(new java.awt.Color(153, 153, 153));
        lamaInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lamaInput.setForeground(new java.awt.Color(51, 51, 51));

        hargaLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(50, 50, 50));
        hargaLabel.setText("Total Harga");

        hargaInput.setBackground(new java.awt.Color(153, 153, 153));
        hargaInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hargaInput.setForeground(new java.awt.Color(51, 51, 51));

        fasilitasLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        fasilitasLabel.setForeground(new java.awt.Color(50, 50, 50));
        fasilitasLabel.setText("Fasilitas");

        snackCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        snackCheck.setText("Snack");
        snackCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snackCheckActionPerformed(evt);
            }
        });

        maskerCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maskerCheck.setText("Masker");

        tissueCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tissueCheck.setText("Tissue");

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(customerDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kendaraanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kendaraanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lamaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lamaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(snackCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maskerCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tissueCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fasilitasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cancelBtn)
                        .addGap(45, 45, 45)
                        .addComponent(saveBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {maskerCheck, snackCheck, tissueCheck});

        inputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, saveBtn});

        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kendaraanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(lamaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lamaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(fasilitasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snackCheck)
                            .addComponent(maskerCheck)
                            .addComponent(tissueCheck))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(customerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(hargaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn)
                            .addComponent(saveBtn))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        tablePenyewaan.setBackground(new java.awt.Color(255, 255, 255));
        tablePenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenyewaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenyewaan);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(tablePanel);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actionBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {actionBar, header, inputPanel, jScrollPane2});

        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(actionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        clearText();
        searchInput.setText("");
        action = "Tambah";
        kendaraanDropdown.setSelectedIndex(0);
        customerDropdown.setSelectedIndex(0);
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        action = "Ubah";
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yakin ingin menghapus data? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    penyewaanControl.deleteDataPenyewaan(selectedId);
                    clearText();
                    showPenyewaan();
                    setComponent(false);
                    setEditDeleteBtn(false);
                }catch(Exception e){
                    System.out.println("Error : "+e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void snackCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snackCheckActionPerformed

    private void tablePenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenyewaanMouseClicked
        // TODO add your handling code here:
        int indexKendaraan = -1;
        int indexCustomer = -1;
        setEditDeleteBtn(true);
        
        setComponent(false);
        
        int clickedRow = tablePenyewaan.getSelectedRow();
        TableModel tableModel = tablePenyewaan.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
        lamaInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        hargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        String fasilitas = tableModel.getValueAt(clickedRow, 5).toString();
        if(fasilitas.contains("Snack")){
            snackCheck.setSelected(true);
        }
        if(fasilitas.contains("Masker")){
            maskerCheck.setSelected(true);
        }
        if(fasilitas.contains("Tissue")){
            tissueCheck.setSelected(true);
        }
        
        String idKendaraan = tableModel.getValueAt(clickedRow, 9).toString();
        System.out.println("\n"+idKendaraan);
        for(Kendaraan kendaraan : listKendaraan){
            if(kendaraan.getId().equals(idKendaraan)){
                indexKendaraan = listKendaraan.indexOf(kendaraan);
            }
        }
        kendaraanDropdown.setSelectedIndex(indexKendaraan);
        int idCustomer = Integer.parseInt(tableModel.getValueAt(clickedRow, 10).toString());
        for(Customer customer : listCustomer){
            if(customer.getId() == idCustomer){
                indexCustomer = listCustomer.indexOf(customer);
            }
        }
        customerDropdown.setSelectedIndex(indexCustomer);
    }//GEN-LAST:event_tablePenyewaanMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try{
            inputKosongException();
            String fasilitas = "-";
            String snack = "";
            String masker = "";
            String tissue = "";
            int selectedIndexKendaraan = kendaraanDropdown.getSelectedIndex();
            Kendaraan selectedKendaraan = listKendaraan.get(selectedIndexKendaraan);
            
            int selectedIndexCustomer = customerDropdown.getSelectedIndex();
            Customer selectedCustomer = listCustomer.get(selectedIndexCustomer);
            
            if(snackCheck.isSelected()){
                snack = "Snack,";
            }
            if(maskerCheck.isSelected()){
                masker = "Masker,";
            }
            if(tissueCheck.isSelected()){
                tissue = "Tissue";
            }
            
            fasilitas = snack + masker + tissue;
            if(fasilitas.length() > 0 && fasilitas.charAt(fasilitas.length()-1) == ','){
                fasilitas = fasilitas.substring(0, fasilitas.length()-1);
            }
            
            if(action.equals("Tambah")){
                Penyewaan p = new Penyewaan(lamaInput.getText(), Float.parseFloat(hargaInput.getText()), fasilitas, selectedKendaraan, selectedCustomer);
                penyewaanControl.insertDataPenyewaan(p);
            }else{
                Penyewaan p = new Penyewaan(selectedId, lamaInput.getText(), Float.parseFloat(hargaInput.getText()), fasilitas, selectedKendaraan, selectedCustomer);
                penyewaanControl.updateDataPeneywaan(p);
            }
            clearText();
            showPenyewaan();
            setComponent(false);
            setEditDeleteBtn(false);
            
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenyewaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenyewaanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBar;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox<Customer> customerDropdown;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JTextField hargaInput;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JPanel kelompokPanel;
    private javax.swing.JComboBox<Kendaraan> kendaraanDropdown;
    private javax.swing.JLabel kendaraanLabel;
    private javax.swing.JTextField lamaInput;
    private javax.swing.JLabel lamaLabel;
    private javax.swing.JCheckBox maskerCheck;
    private javax.swing.JLabel npm1Label;
    private javax.swing.JLabel npm2Label;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JCheckBox snackCheck;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tablePenyewaan;
    private javax.swing.JCheckBox tissueCheck;
    // End of variables declaration//GEN-END:variables

    public void setComponent(boolean b) {
        kendaraanDropdown.setEnabled(b);
        customerDropdown.setEnabled(b);
        snackCheck.setEnabled(b);
        maskerCheck.setEnabled(b);
        tissueCheck.setEnabled(b);
        snackCheck.setSelected(b);
        maskerCheck.setSelected(b);
        tissueCheck.setSelected(b);
        lamaInput.setEnabled(b);
        hargaInput.setEnabled(b);
        
        saveBtn.setEnabled(b);
        cancelBtn.setEnabled(b);
    }

    public void setEditDeleteBtn(boolean b) {
        editBtn.setEnabled(b);
        deleteBtn.setEnabled(b);
    }
    
    public void clearText(){
        lamaInput.setText("");
        hargaInput.setText("");
        kendaraanDropdown.setSelectedItem(ABORT);
        customerDropdown.setSelectedItem(ABORT);
        snackCheck.setSelected(false);
        maskerCheck.setSelected(false);
        tissueCheck.setSelected(false);
        
        searchInput.setText("");
    }

    public void showPenyewaan() {
        tablePenyewaan.setModel(penyewaanControl.showDataPenyewaan(""));
    }

    public void setKendaraanToDropdown() {
        listKendaraan = kendaraanControl.showListKendaraan();
        for(int i = 0; i < listKendaraan.size(); i++){
            kendaraanDropdown.addItem(listKendaraan.get(i));
        }
    }

    public void setCustomerToDropdown() {
        listCustomer = customerControl.showListCustomer();
        for(int i = 0; i < listCustomer.size();i++){
            customerDropdown.addItem(listCustomer.get(i));
        }
    }
    
    public void inputKosongException() throws InputKosongException{
        if(lamaInput.getText().isEmpty() || hargaInput.getText().isEmpty() || kendaraanDropdown.getSelectedIndex() == -1){
            throw new InputKosongException();
        }
    }
}
